# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170520_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('salt', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_id',
        ),
        migrations.AlterField(
            model_name='assignementstudent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
