# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20170520_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='teachercourse',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='teachercourse',
            name='teacher_id',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
        migrations.DeleteModel(
            name='TeacherCourse',
        ),
    ]
