# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170520_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Role',
        ),
    ]
