# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 19:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20170520_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='teacher_id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='course',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
