# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170522_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user_id',
        ),
    ]
