# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_course_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='user_id',
            new_name='user',
        ),
    ]
