# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20170523_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(through='app.UserCourse', to=settings.AUTH_USER_MODEL),
        ),
    ]
