# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_course_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
