# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_usercourse_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='games',
            field=models.ManyToManyField(through='app.GameCourse', to='app.Game'),
        ),
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
