# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_usercourse_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='games',
            field=models.ManyToManyField(through='app.GameCourse', to='app.Game'),
        ),
        migrations.AddField(
            model_name='course',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='static/pictures/'),
        ),
    ]
